# Generated by Django 5.2.4 on 2025-08-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('banner_title', models.CharField(default='About Us', max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('description_top', models.TextField()),
                ('description_bottom', models.TextField()),
                ('why_title', models.CharField(default='Why Choose Us?', max_length=100)),
                ('why_collection', models.TextField()),
                ('why_affordable', models.TextField()),
                ('why_hygiene', models.TextField()),
                ('why_convenient', models.TextField()),
            ],
        ),
    ]
