# Generated by Django 5.2.4 on 2025-08-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('right_side_image', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('description', models.TextField()),
                ('phone', models.CharField(default='+911234567890', max_length=20)),
                ('fax', models.CharField(default='0421 455 4555', max_length=20)),
                ('email', models.EmailField(default='info@mailjewellery.com', max_length=254)),
            ],
        ),
    ]
