# Generated by Django 5.2.4 on 2025-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productcategory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='featured/')),
                ('button_text', models.CharField(default='Explore', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('left', 'Image Left'), ('right', 'Image Right')], default='left', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('button_text', models.CharField(default='Rent Now', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='promo/')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='promo/')),
            ],
        ),
    ]
