# Generated by Django 5.2.4 on 2025-08-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('message', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
