# Generated by Django 5.2.4 on 2025-08-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_banners/')),
                ('title', models.CharField(max_length=100)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='core.productcategory')),
            ],
        ),
    ]
