# Generated by Django 5.0.6 on 2025-11-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categorybanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parent_categories/')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller first in listing')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parent Category',
                'verbose_name_plural': 'Parent Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParentCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='order of this subcategory under the parent')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_assignment', to='core.productcategory')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.parentcategory')),
            ],
            options={
                'verbose_name': 'Parent → Subcategory assignment',
                'verbose_name_plural': 'Parent → Subcategory assignments',
                'ordering': ['parent', 'order'],
            },
        ),
    ]
