# Generated by Django 5.0.6 on 2025-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productrecommendation_userproductinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
