# Generated by Django 5.0.6 on 2025-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_metal_alter_product_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommended_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
