# Generated by Django 5.0.6 on 2025-12-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productrecommendation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='also_bought_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
